### ISSUE TITLE
No issues here!

### ISSUE THREAD

**Issue by Joe-V2** [volkanto/fitbit-mountain-face#2]
I just wanted to reach out and say thank you, although it seems this form is the only way to attach a comment to a repo... I'm still new to this though, so feel free to correct me!

Used NPM, and with a few lines in powershell I got this thing running on the Fitbit Versa I received as a hand-me-down. Immediately, I found myself inspired to get to work - current objectives include an altimeter display continuing with the mountain theme, as well as using the sky as a daylight meter, reflecting how much sunlight - or moonlight - is left. Already made the icons for the phases of the latter, just need to get them working!

Again, my sincere thanks. You've helped rekindle my love for programming, and I can't wait to get started!

**Comment by volkanto** [comment]
Hey Joe,

Thanks for your feedback and I am really glad to see your comment here. I think there is no proper way to send your comments but creating an issue is another way to do this :) It is really a pleasure for me to get feedback and also to hear your plan about your fork. 

I am looking forward to seeing your progress and also don't hesitate to reach out.

**Comment by Joe-V2** [comment]
Hey Volkanto,

I've just finished everything I set out to do - I moved it into my own private repo for exclusivity's sake, but I would be very happy indeed to grant you access so you can try it for yourself!

**Comment by volkanto** [comment]
hey @Joe-V2 ,

Sure, feel free to add me to your repo and really interested in checking what you've done so far.
